version: '3.7'

# Base docker compose file, docker-compose.override will automatically be read and merged with this file
services:

  db:
    image: mysql:8

  api:
    build:
      context: ./openfda
    depends_on:
      - db
