version: '3.7'


services:
   
    drugs:
        container_name: drugs
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8082:8080
        volumes:
            - ./data:/app/data